export default {
  'allContent---uk-ua-docusaurus-debug-content-246-fe3': [() => import(/* webpackChunkName: 'allContent---uk-ua-docusaurus-debug-content-246-fe3' */ '~debug/default/docusaurus-debug-all-content-673.json'), '~debug/default/docusaurus-debug-all-content-673.json', require.resolveWeak('~debug/default/docusaurus-debug-all-content-673.json')],
  'component---theme-debug-config-23-a-2ff': [() => import(/* webpackChunkName: 'component---theme-debug-config-23-a-2ff' */ '@theme/DebugConfig'), '@theme/DebugConfig', require.resolveWeak('@theme/DebugConfig')],
  'component---theme-debug-contentba-8-ce7': [() => import(/* webpackChunkName: 'component---theme-debug-contentba-8-ce7' */ '@theme/DebugContent'), '@theme/DebugContent', require.resolveWeak('@theme/DebugContent')],
  'component---theme-debug-global-dataede-0fa': [() => import(/* webpackChunkName: 'component---theme-debug-global-dataede-0fa' */ '@theme/DebugGlobalData'), '@theme/DebugGlobalData', require.resolveWeak('@theme/DebugGlobalData')],
  'component---theme-debug-registry-679-501': [() => import(/* webpackChunkName: 'component---theme-debug-registry-679-501' */ '@theme/DebugRegistry'), '@theme/DebugRegistry', require.resolveWeak('@theme/DebugRegistry')],
  'component---theme-debug-routes-946-699': [() => import(/* webpackChunkName: 'component---theme-debug-routes-946-699' */ '@theme/DebugRoutes'), '@theme/DebugRoutes', require.resolveWeak('@theme/DebugRoutes')],
  'component---theme-debug-site-metadata-68-e-3d4': [() => import(/* webpackChunkName: 'component---theme-debug-site-metadata-68-e-3d4' */ '@theme/DebugSiteMetadata'), '@theme/DebugSiteMetadata', require.resolveWeak('@theme/DebugSiteMetadata')],
  'component---theme-doc-item-178-a40': [() => import(/* webpackChunkName: 'component---theme-doc-item-178-a40' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  'component---theme-doc-page-1-be-9be': [() => import(/* webpackChunkName: 'component---theme-doc-page-1-be-9be' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  'component---theme-mdx-page-1-f-3-b90': [() => import(/* webpackChunkName: 'component---theme-mdx-page-1-f-3-b90' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  'content---uk-ua-b-21-b71': [() => import(/* webpackChunkName: 'content---uk-ua-b-21-b71' */ '@site/i18n/uk-ua/docusaurus-plugin-content-docs/current/readme.md'), '@site/i18n/uk-ua/docusaurus-plugin-content-docs/current/readme.md', require.resolveWeak('@site/i18n/uk-ua/docusaurus-plugin-content-docs/current/readme.md')],
  'content---uk-ua-markdown-page-393-e2e': [() => import(/* webpackChunkName: 'content---uk-ua-markdown-page-393-e2e' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  'versionMetadata---uk-ua-935-6df': [() => import(/* webpackChunkName: 'versionMetadata---uk-ua-935-6df' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],};
